# Default values for submission-errors.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hmda/submission-errors
  tag: v2.7.2
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

kafka:
  modifiedLarGroup: submission-errors-group
  modifiedLarTopic: hmda-submission-errors
  signTopic: hmda-sign
  security: ""

logs:
  cassandra: TRACE

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

service:
  account:
    name: hmda-platform

resources:
  limits:
    memory: "6200Mi"
    cpu: "4"
  requests:
    memory: "3200Mi"
    cpu: "1"
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

hmda:
  platform:
    rds:
      secret:
        name: submission-errors-secrets
        keys:
          host: hmda-rds-host
          database: hmda-rds-db
          username: hmda-rds-username
          password: hmda-rds-password
    cassandra:
      host: localhost:9042
      dc: main
      journal: hmda2_journal
      snapshot: hmda2_snapshot
      secret:
        name: submission-errors-secrets
        keys:
          username: cassandra.username
          password: cassandra.password
  ssm:
    name: submission-errors-secrets-provider
    usePodIdentity: "false"
    objects:
      - objectName: ""
        objectType: "secretsmanager"
        jmesPath:
          - path: ""
            objectAlias: "hmda-rds-username"
          - path: ""
            objectAlias: "hmda-rds-password"
          - path: ""
            objectAlias: "hmda-rds-host"
          - path: ""
            objectAlias: "hmda-rds-db"
      - objectName: ""
        objectType: "secretsmanager"
        jmesPath:
          - path: ""
            objectAlias: "cassandra.username"
          - path: ""
            objectAlias: "cassandra.password"
    secretObjects:
      - data:
          - key: hmda-rds-username
            objectName: hmda-rds-username
          - key: hmda-rds-password
            objectName: hmda-rds-password
          - key: hmda-rds-host
            objectName: hmda-rds-host
          - key: hmda-rds-db
            objectName: hmda-rds-db
          - key: cassandra.username
            objectName: cassandra.username
          - key: cassandra.password
            objectName: cassandra.password
        secretName: submission-errors-secrets
        type: Opaque