package hmda.analytics.query

import hmda.model.filing.lar.LoanApplicationRegister

object LarConverter {

  def apply(lar: LoanApplicationRegister): LarEntity = {
    LarEntity(
      lar.larIdentifier.id,
      lar.larIdentifier.LEI,
      lar.loan.ULI,
      lar.loan.applicationDate,
      lar.loan.loanType.code,
      lar.loan.loanPurpose.code,
      lar.action.preapproval.code,
      lar.loan.constructionMethod.code,
      lar.loan.occupancy.code,
      lar.loan.amount,
      lar.action.actionTakenType.code,
      lar.action.actionTakenDate,
      lar.geography.street,
      lar.geography.city,
      lar.geography.state,
      lar.geography.zipCode,
      lar.geography.county,
      lar.geography.tract,
      lar.applicant.ethnicity.ethnicity1.code,
      lar.applicant.ethnicity.ethnicity2.code,
      lar.applicant.ethnicity.ethnicity3.code,
      lar.applicant.ethnicity.ethnicity4.code,
      lar.applicant.ethnicity.ethnicity5.code,
      lar.applicant.ethnicity.otherHispanicOrLatino, //24
      lar.coApplicant.ethnicity.ethnicity1.code,
      lar.coApplicant.ethnicity.ethnicity2.code,
      lar.coApplicant.ethnicity.ethnicity3.code,
      lar.coApplicant.ethnicity.ethnicity4.code,
      lar.coApplicant.ethnicity.ethnicity5.code,
      lar.coApplicant.ethnicity.otherHispanicOrLatino,
      lar.applicant.ethnicity.ethnicityObserved.code,
      lar.coApplicant.ethnicity.ethnicityObserved.code,
      lar.applicant.race.race1.code,
      lar.applicant.race.race2.code,
      lar.applicant.race.race3.code,
      lar.applicant.race.race4.code,
      lar.applicant.race.race5.code,
      lar.applicant.race.otherNativeRace,
      lar.applicant.race.otherAsianRace,
      lar.applicant.race.otherPacificIslanderRace,
      lar.coApplicant.race.race1.code,
      lar.coApplicant.race.race2.code,
      lar.coApplicant.race.race3.code,
      lar.coApplicant.race.race4.code,
      lar.coApplicant.race.race5.code,
      lar.coApplicant.race.otherNativeRace,
      lar.coApplicant.race.otherAsianRace,
      lar.coApplicant.race.otherPacificIslanderRace,
      lar.applicant.race.raceObserved.code,
      lar.coApplicant.race.raceObserved.code,
      lar.applicant.sex.sexEnum.code,
      lar.coApplicant.sex.sexEnum.code,
      lar.applicant.sex.sexObservedEnum.code,
      lar.coApplicant.sex.sexObservedEnum.code,
      lar.applicant.age,
      lar.coApplicant.age,
      lar.income,
      lar.purchaserType.code,
      lar.loan.rateSpread,
      lar.hoepaStatus.code,
      lar.lienStatus.code,
      lar.applicant.creditScore,
      lar.coApplicant.creditScore,
      lar.applicant.creditScoreType.code,
      lar.applicant.otherCreditScoreModel,
      lar.coApplicant.creditScoreType.code,
      lar.coApplicant.otherCreditScoreModel,
      lar.denial.denialReason1.code,
      lar.denial.denialReason2.code,
      lar.denial.denialReason3.code,
      lar.denial.denialReason4.code, //71
      lar.denial.otherDenialReason,
      lar.loanDisclosure.totalLoanCosts,
      lar.loanDisclosure.totalPointsAndFees, //,
      lar.loanDisclosure.originationCharges, //, //75
      lar.loanDisclosure.discountPoints,
      lar.loanDisclosure.lenderCredits, //,
      lar.loan.interestRate, //,
      lar.loan.prepaymentPenaltyTerm, //,
      lar.loan.debtToIncomeRatio,
      lar.loan.combinedLoanToValueRatio,
      lar.loan.loanTerm,
      lar.loan.introductoryRatePeriod,
      lar.nonAmortizingFeatures.balloonPayment.code,
      lar.nonAmortizingFeatures.interestOnlyPayments.code,
      lar.nonAmortizingFeatures.negativeAmortization.code,
      lar.nonAmortizingFeatures.otherNonAmortizingFeatures.code,
      lar.property.propertyValue,
      lar.property.manufacturedHomeSecuredProperty.code,
      lar.property.manufacturedHomeLandPropertyInterest.code, //, //90
      lar.property.totalUnits,
      lar.property.multiFamilyAffordableUnits,
      lar.applicationSubmission.code,
      lar.payableToInstitution.code,
      lar.larIdentifier.NMLSRIdentifier,
      lar.AUS.aus1.code,
      lar.AUS.aus2.code,
      lar.AUS.aus3.code,
      lar.AUS.aus4.code,
      lar.AUS.aus5.code,
      lar.AUS.otherAUS,
      lar.ausResult.ausResult1.code,
      lar.ausResult.ausResult2.code,
      lar.ausResult.ausResult3.code,
      lar.ausResult.ausResult4.code,
      lar.ausResult.ausResult5.code,
      lar.ausResult.otherAusResult,
      lar.reverseMortgage.code,
      lar.lineOfCredit.code,
      lar.businessOrCommercialPurpose.code
    )
  }

}
