pipeline {
  agent {
    label 'hmdaops'
  }

  stages {
    stage('init') {
      steps {
        script {
          library identifier: "hmdaUtils@master", retriever: modernSCM (
              [
                  $class: 'GitSCMSource',
                  remote: 'https://github.cfpb.gov/HMDA-Operations/hmda-devops.git'
              ]
          )

          init.setEnvironment('auth')
          init.checkForChanges('auth')
        }
      }
    }

     stage('Build and package Java Code') {
       agent {
        docker {
          image 'hmda/maven'
          reuseNode true
        }
      }
       steps {
         sh "mvn -B -f ./auth/ clean package"
       }
     }

    stage('Build And Publish Docker Image') {
      steps {
        script {
          withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub',
            usernameVariable: 'DOCKER_HUB_USER', passwordVariable: 'DOCKER_HUB_PASSWORD']]) {
            withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'hmda-platform-jenkins-service',
              usernameVariable: 'DTR_USER', passwordVariable: 'DTR_PASSWORD']]) {
              withCredentials([string(credentialsId: 'internal-docker-registry', variable: 'DOCKER_REGISTRY_URL')]){
                dockerBuild.dockerBuild('auth', 'auth/')
                security.dockerImageScan('auth', env.DOCKER_TAG)
              }
            }
          }
        }
      }
    }

  }

}
