pipeline {
  agent {
    label 'hmdaops'
  }

  stages {
    stage('init') {
      steps {
        script {
          init.setEnvironment('auth')
          init.checkForChanges('auth')
        }
      }
    }

     stage('Build and package Java Code') {
       agent {
        docker {
          image 'hmda/maven'
          reuseNode true
        }
      }
       steps {
         sh "mvn -B -f ./auth/ clean package"
         sh "rm -rf data"
       }
     }

    stage('Build And Publish Docker Image') {
      steps {
        script {
          withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub',
            usernameVariable: 'DOCKER_HUB_USER', passwordVariable: 'DOCKER_HUB_PASSWORD']]) {
            withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dtr-ext-jenkins-service',
              usernameVariable: 'DTR_USER', passwordVariable: 'DTR_PASSWORD']]) {
                dockerBuild.dockerBuild('auth', 'auth/')
                scanImage('hmda/auth', env.DOCKER_TAG)
            }
          }
        }
      }
    }

  }

}
