pipeline {
  agent {
    label 'hmdaops'
  }

  stages {
    stage('init') {
      steps {
        script {
          library identifier: "hmdaUtils@master", retriever: modernSCM (
              [
                  $class: 'GitSCMSource',
                  remote: 'https://github.cfpb.gov/HMDA-Operations/hmda-devops.git'
              ]
          )

          init.setEnvironment('check_digit')
          init.checkForChanges('check-digit')
        }
      }
    }

    stage('Build Scala Code and Generate Dockerfile') {
      agent {
        docker {
          image 'hmda/sbt'
          reuseNode true
        }
      }
      steps {
        sh """find . -name target -type d -prune -exec rm -rf {} \\;"""
        sh "sbt -Dsbt.global.base=.sbt -Dsbt.boot.directory=.sbt -Dsbt.ivy.home=.ivy2 -batch clean check-digit/docker:stage"
        sh "rm -rf data"
      }
    }

    stage('Build And Publish Docker Image') {
      steps {
        script {
          withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub',
            usernameVariable: 'DOCKER_HUB_USER', passwordVariable: 'DOCKER_HUB_PASSWORD']]) {
            withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'hmda-platform-jenkins-service',
              usernameVariable: 'DTR_USER', passwordVariable: 'DTR_PASSWORD']]) {
              withCredentials([string(credentialsId: 'internal-docker-registry', variable: 'DOCKER_REGISTRY_URL')]){
                dockerBuild.sbtBuild('check-digit')
                scanImage('check-digit', env.DOCKER_TAG)
              }
            }
          }
        }
      }
    }

    stage('Deploy') {
      agent {
        docker {
          image 'hmda/helm'
          reuseNode true
          args '--entrypoint=\'\''
        }
      }
      steps {
        script {
          withCredentials([file(credentialsId: 'hmda-ops-kubeconfig', variable: 'KUBECONFIG')]) {
            if (env.DOCKER_PUSH == 'true') {
              helm.deploy('check-digit')
            }
          }
        }
      }
    }

    stage('Docker Clean Up') {
      steps {
        script {
          dockerBuild.clean()
        }
      }
    }
  }

}
