apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "email-service.fullname" . }}
  annotations:
    reloader.stakater.com/search: "true"
  labels:
    app: {{ template "email-service.name" . }}
    chart: {{ template "email-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "email-service.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "email-service.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/America/New_York    
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime          
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL            
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: inst-postgres-credentials
                  key: url
            - name: KAFKA_CLUSTER_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: kafka.hosts
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws-secret-access-key
            - name: AWS_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: s3-configmap
                  key: aws-environment
            - name: BANK_FILTER_LIST
              valueFrom:
                configMapKeyRef:
                  name: bank-filter-configmap
                  key: bank-filter-list
            - name: EMAIL_LOG_LEVEL
              value: INFO
            - name: KAFKA_EMAIL_TOPIC
              value: {{.Values.kafka.emailTopic}}
            - name: KAFKA_EMAIL_CONSUMER_GROUP_ID
              value: {{.Values.kafka.emailGroup}}
            {{- if .Values.kafka.security }}
            - name: KAFKA_SECURITY
              value: {{.Values.kafka.security}}
            {{- end }}              
            - name: EMAIL_SUBJECT
              valueFrom:
                configMapKeyRef:
                  name: email-configmap
                  key: emailSubject
            - name: EMAIL_CONTENT
              valueFrom:
                configMapKeyRef:
                  name: email-configmap
                  key: emailContent
            - name: SENDER_EMAIL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: email-configmap
                  key: emailSender
            - name: HMDA_ADMIN_EMIAL
              valueFrom:
                configMapKeyRef:
                  name: email-configmap
                  key: adminEmailAddress
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
