apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "email-service.fullname" . }}
  annotations:
    reloader.stakater.com/search: "true"
  labels:
    app: {{ template "email-service.name" . }}
    chart: {{ template "email-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "email-service.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "email-service.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.service.account.name }}
      volumes:
        - name: rds-secrets-vol
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: irsa-hmda-rds-secrets-provider
        - name: smtp-secrets-vol
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: smtp-provider
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/America/New_York
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name: rds-secrets-vol
              mountPath: /mnt/rds-secrets
            - name: smtp-secrets-vol
              mountPath: /mnt/smtp-secrets
            - name: tz-config
              mountPath: /etc/localtime
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL            
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
#            - name: JDBC_URL
#              valueFrom:
#                secretKeyRef:
#                  name: inst-postgres-credentials
#                  key: url
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: irsa-platform-rds-secrets
                  key: host
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: irsa-platform-rds-secrets
                  key: database
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: irsa-platform-rds-secrets
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: irsa-platform-rds-secrets
                  key: password
            - name: KAFKA_CLUSTER_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: kafka.hosts
#            - name: AWS_ACCESS_KEY_ID
#              valueFrom:
#                secretKeyRef:
#                  name: aws-credentials
#                  key: aws-access-key-id
#            - name: AWS_SECRET_ACCESS_KEY
#              valueFrom:
#                secretKeyRef:
#                  name: aws-credentials
#                  key: aws-secret-access-key
            - name: AWS_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: s3-configmap
                  key: aws-environment
            - name: BANK_FILTER_LIST
              valueFrom:
                configMapKeyRef:
                  name: bank-filter-configmap
                  key: bank-filter-list
            - name: EMAIL_LOG_LEVEL
              value: INFO
            - name: KAFKA_EMAIL_TOPIC
              value: {{.Values.kafka.emailTopic}}
            - name: KAFKA_EMAIL_CONSUMER_GROUP_ID
              value: {{.Values.kafka.emailGroup}}
            {{- if .Values.kafka.security }}
            - name: KAFKA_SECURITY
              value: {{.Values.kafka.security}}
            {{- end }}              
            - name: EMAIL_SUBJECT
              valueFrom:
                configMapKeyRef:
                  name: email-configmap
                  key: emailSubject
            - name: EMAIL_CONTENT
              valueFrom:
                configMapKeyRef:
                  name: email-configmap
                  key: emailContent
            - name: SENDER_EMAIL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: email-configmap
                  key: emailSender
            - name: HMDA_ADMIN_EMIAL
              valueFrom:
                configMapKeyRef:
                  name: email-configmap
                  key: adminEmailAddress
            - name: EMAIL_PROTOCOL
              value: smtp
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: smtp-secrets
                  key: host
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: smtp-secrets
                  key: port
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smtp-secrets
                  key: username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-secrets
                  key: password
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
