package hmda.model.filing.lar

object LarFieldMapping {
  def mapping(lar: LoanApplicationRegister): Map[String, String] = Map(
    "Record Identifier" -> lar.larIdentifier.id.toString,
    "Legal Entity Identifier" -> lar.larIdentifier.LEI,
    "Universal Loan Identifier" -> lar.loan.ULI,
    "Application Date" -> lar.loan.applicationDate,
    "Loan Type" -> lar.loan.loanType.code.toString,
    "Loan Purpose" -> lar.loan.loanPurpose.code.toString,
    "Preapproval" -> lar.action.preapproval.code.toString,
    "Construction Method" -> lar.loan.constructionMethod.code.toString,
    "Occupancy Type" -> lar.loan.occupancy.code.toString,
    "Loan Amount" -> lar.loan.amount.toString,
    "Action Taken" -> lar.action.actionTakenType.code.toString,
    "Action Taken Date" -> lar.action.actionTakenDate.toString,
    "Street Address" -> lar.geography.street,
    "City" -> lar.geography.city,
    "State" -> lar.geography.state,
    "Zip Code" -> lar.geography.zipCode,
    "County" -> lar.geography.county,
    "Census Tract" -> lar.geography.tract,
    "Applicant Ethnicity 1" -> lar.applicant.ethnicity.ethnicity1.code.toString,
    "Applicant Ethnicity 2" -> lar.applicant.ethnicity.ethnicity2.code.toString,
    "Applicant Ethnicity 3" -> lar.applicant.ethnicity.ethnicity3.code.toString,
    "Applicant Ethnicity 4" -> lar.applicant.ethnicity.ethnicity4.code.toString,
    "Applicant Ethnicity 5" -> lar.applicant.ethnicity.ethnicity5.code.toString,
    "Other Hispanic Applicant Ethnicity" -> lar.applicant.ethnicity.otherHispanicOrLatino,
    "Co-Applicant Ethnicity 1" -> lar.coApplicant.ethnicity.ethnicity1.code.toString,
    "Co-Applicant Ethnicity 2" -> lar.coApplicant.ethnicity.ethnicity2.code.toString,
    "Co-Applicant Ethnicity 3" -> lar.coApplicant.ethnicity.ethnicity3.code.toString,
    "Co-Applicant Ethnicity 4" -> lar.coApplicant.ethnicity.ethnicity4.code.toString,
    "Co-Applicant Ethnicity 1" -> lar.coApplicant.ethnicity.ethnicity5.code.toString,
    "Other Hispanic Co-Applicanty Ethnicity" -> lar.coApplicant.ethnicity.otherHispanicOrLatino,
    "Applicant Ethnicity Observed" -> lar.applicant.ethnicity.ethnicityObserved.code.toString,
    "Co-Applicant Ethnicity Observed" -> lar.coApplicant.ethnicity.ethnicityObserved.code.toString,
    "Applicant Race 1" -> lar.applicant.race.race1.code.toString,
    "Applicant Race 2" -> lar.applicant.race.race2.code.toString,
    "Applicant Race 3" -> lar.applicant.race.race3.code.toString,
    "Applicant Race 4" -> lar.applicant.race.race4.code.toString,
    "Applicant Race 5" -> lar.applicant.race.race5.code.toString,
    "Other Native Applicant Race" -> lar.applicant.race.otherNativeRace,
    "Other Asian Applicant Race" -> lar.applicant.race.otherAsianRace,
    "Other Pacific Applicant Race" -> lar.applicant.race.otherPacificIslanderRace,
    "Co-Applicant Race 1" -> lar.coApplicant.race.race1.code.toString,
    "Co-Applicant Race 2" -> lar.coApplicant.race.race2.code.toString,
    "Co-Applicant Race 3" -> lar.coApplicant.race.race3.code.toString,
    "Co-Applicant Race 4" -> lar.coApplicant.race.race4.code.toString,
    "Co-Applicant Race 5" -> lar.coApplicant.race.race5.code.toString,
    "Other Native Co-Applicant Race" -> lar.coApplicant.race.otherNativeRace,
    "Other Asian Co-Applicant Race" -> lar.coApplicant.race.otherAsianRace,
    "Other Pacific Co-Applicant Race" -> lar.coApplicant.race.otherPacificIslanderRace,
    "Applicant Race Observed" -> lar.applicant.race.raceObserved.code.toString,
    "Co-Applicant Race Observed" -> lar.coApplicant.race.raceObserved.code.toString,
    "Applicant Sex" -> lar.applicant.sex.sexEnum.code.toString,
    "Co-Applicant Sex" -> lar.coApplicant.sex.sexEnum.code.toString,
    "Applicant Sex Observed" -> lar.applicant.sex.sexObservedEnum.code.toString,
    "Co-Applicant Sex Observed" -> lar.coApplicant.sex.sexObservedEnum.code.toString,
    "Applicant Age" -> lar.applicant.age.toString,
    "Co-Applicant Age" -> lar.coApplicant.age.toString,
    "Income" -> lar.income,
    "Type of Purchaser" -> lar.purchaserType.code.toString,
    "Rate Spread" -> lar.loan.rateSpread,
    "HOEPA Status" -> lar.hoepaStatus.code.toString,
    "Lien Status" -> lar.lienStatus.code.toString,
    "Applicant Credit Score" -> lar.applicant.creditScore.toString,
    "Co-Applicant Credit Score" -> lar.coApplicant.creditScore.toString,
    "Applicant Credit Scoring Model" -> lar.applicant.creditScoreType.code.toString,
    "Other Applicant Credit Scoring Model" -> lar.applicant.otherCreditScoreModel,
    "Co-Applicant Credit Scoring Model" -> lar.coApplicant.creditScoreType.code.toString,
    "Other Co-Applicant Credit Scoring Model" -> lar.coApplicant.otherCreditScoreModel,
    "Reason for Denial 1" -> lar.denial.denialReason1.code.toString,
    "Reason for Denial 2" -> lar.denial.denialReason2.code.toString,
    "Reason for Denial 3" -> lar.denial.denialReason3.code.toString,
    "Reason for Denial 4" -> lar.denial.denialReason4.code.toString,
    "Other Reason for Denial" -> lar.denial.otherDenialReason,
    "Total Loan Costs" -> lar.loanDisclosure.totalLoanCosts,
    "Total Points and Fees" -> lar.loanDisclosure.totalPointsAndFees,
    "Origination Charges" -> lar.loanDisclosure.originationCharges,
    "Discount Points" -> lar.loanDisclosure.discountPoints,
    "Lender Credits" -> lar.loanDisclosure.lenderCredits,
    "Interest Rate" -> lar.loan.interestRate,
    "Prepayment Penalty Term" -> lar.loan.prepaymentPenaltyTerm,
    "Debt-to-Income Ration" -> lar.loan.debtToIncomeRatio,
    "Combined Loan-to-Value Ration" -> lar.loan.combinedLoanToValueRatio,
    "Loan Term" -> lar.loan.loanTerm,
    "Introductory Rate Period" -> lar.loan.introductoryRatePeriod,
    "Balloon Payment" -> lar.nonAmortizingFeatures.balloonPayment.code.toString,
    "Interest-Only Payments" -> lar.nonAmortizingFeatures.interestOnlyPayments.code.toString,
    "Negative Amortization" -> lar.nonAmortizingFeatures.negativeAmortization.code.toString,
    "Other Non-amortizing Features" -> lar.nonAmortizingFeatures.otherNonAmortizingFeatures.code.toString,
    "Property Value" -> lar.property.propertyValue,
    "Manufactured Home Secured Property Type" -> lar.property.manufacturedHomeSecuredProperty.code.toString,
    "Manufactured Home Land Property Interest" -> lar.property.manufacturedHomeLandPropertyInterest.code.toString,
    "Total Units" -> lar.property.totalUnits.toString,
    "Multifamily Affordable Units" -> lar.property.multiFamilyAffordableUnits,
    "Submission of Application" -> lar.applicationSubmission.code.toString,
    "Initially Payable to Your Institution" -> lar.payableToInstitution.code.toString,
    "Mortgage Loan Originator NMLSR Identifier" -> lar.larIdentifier.NMLSRIdentifier,
    "Automated Underwriting System 1" -> lar.AUS.aus1.code.toString,
    "Automated Underwriting System 2" -> lar.AUS.aus2.code.toString,
    "Automated Underwriting System 3" -> lar.AUS.aus3.code.toString,
    "Automated Underwriting System 4" -> lar.AUS.aus4.code.toString,
    "Automated Underwriting System 5" -> lar.AUS.aus5.code.toString,
    "Automated Underwriting System: Conditional Free Form Text Field for Code 5" -> lar.AUS.otherAUS,
    "Automated Underwriting System Result 1" -> lar.ausResult.ausResult1.code.toString,
    "Automated Underwriting System Result 2" -> lar.ausResult.ausResult2.code.toString,
    "Automated Underwriting System Result 3" -> lar.ausResult.ausResult3.code.toString,
    "Automated Underwriting System Result 4" -> lar.ausResult.ausResult4.code.toString,
    "Automated Underwriting System Result 5" -> lar.ausResult.ausResult5.code.toString,
    "Automated Underwriting System Result: Conditional Free Form Text Field for Code 16" -> lar.ausResult.otherAusResult,
    "Reverse Mortgage" -> lar.reverseMortgage.code.toString,
    "Open-End Line of Credit" -> lar.lineOfCredit.code.toString,
    "Business or Commercial Purpose" -> lar.businessOrCommercialPurpose.code.toString
  )
}
