package hmda.model.filing.lar

object LarFieldMapping {
  def mapping(lar: LoanApplicationRegister): Map[String, String] = Map(
    "All data fields in the LAR"                                                                                                 -> lar.toCSV,
    "Record Identifier"                                                                                                          -> lar.larIdentifier.id.toString,
    "Legal Entity Identifier (LEI)"                                                                                              -> lar.larIdentifier.LEI,
    "Universal Loan Identifier (ULI)"                                                                                            -> lar.loan.ULI,
    "Application Date"                                                                                                           -> lar.loan.applicationDate,
    "Loan Type"                                                                                                                  -> lar.loan.loanType.code.toString,
    "Loan Purpose"                                                                                                               -> lar.loan.loanPurpose.code.toString,
    "Preapproval"                                                                                                                -> lar.action.preapproval.code.toString,
    "Construction Method"                                                                                                        -> lar.loan.constructionMethod.code.toString,
    "Occupancy Type"                                                                                                             -> lar.loan.occupancy.code.toString,
    "Loan Amount"                                                                                                                -> lar.loan.amount.toString,
    "Action Taken"                                                                                                               -> lar.action.actionTakenType.code.toString,
    "Action Taken Date"                                                                                                          -> lar.action.actionTakenDate.toString,
    "Street Address"                                                                                                             -> lar.geography.street,
    "City"                                                                                                                       -> lar.geography.city,
    "State"                                                                                                                      -> lar.geography.state,
    "Zip Code"                                                                                                                   -> lar.geography.zipCode,
    "County"                                                                                                                     -> lar.geography.county,
    "Census Tract"                                                                                                               -> lar.geography.tract,
    "Ethnicity of Applicant or Borrower: 1"                                                                                      -> lar.applicant.ethnicity.ethnicity1.code.toString,
    "Ethnicity of Applicant or Borrower: 2"                                                                                      -> lar.applicant.ethnicity.ethnicity2.code.toString,
    "Ethnicity of Applicant or Borrower: 3"                                                                                      -> lar.applicant.ethnicity.ethnicity3.code.toString,
    "Ethnicity of Applicant or Borrower: 4"                                                                                      -> lar.applicant.ethnicity.ethnicity4.code.toString,
    "Ethnicity of Applicant or Borrower: 5"                                                                                      -> lar.applicant.ethnicity.ethnicity5.code.toString,
    "Ethnicity of Applicant or Borrower: Free Form Text Field for Other Hispanic or Latino"                                      -> lar.applicant.ethnicity.otherHispanicOrLatino,
    "Ethnicity of Co-Applicant or Co-Borrower: 1"                                                                                -> lar.coApplicant.ethnicity.ethnicity1.code.toString,
    "Ethnicity of Co-Applicant or Co-Borrower: 2"                                                                                -> lar.coApplicant.ethnicity.ethnicity2.code.toString,
    "Ethnicity of Co-Applicant or Co-Borrower: 3"                                                                                -> lar.coApplicant.ethnicity.ethnicity3.code.toString,
    "Ethnicity of Co-Applicant or Co-Borrower: 4"                                                                                -> lar.coApplicant.ethnicity.ethnicity4.code.toString,
    "Ethnicity of Co-Applicant or Co-Borrower: 5"                                                                                -> lar.coApplicant.ethnicity.ethnicity5.code.toString,
    "Ethnicity of Co-Applicant or Co-Borrower: Free Form Text Field for Other Hispanic or Latino"                                -> lar.coApplicant.ethnicity.otherHispanicOrLatino,
    "Ethnicity of Applicant or Borrower Collected on the Basis of Visual Observation or Surname"                                 -> lar.applicant.ethnicity.ethnicityObserved.code.toString,
    "Ethnicity of Co-Applicant or Co-Borrower Collected on the Basis of Visual Observation or Surname"                           -> lar.coApplicant.ethnicity.ethnicityObserved.code.toString,
    "Race of Applicant or Borrower: 1"                                                                                           -> lar.applicant.race.race1.code.toString,
    "Race of Applicant or Borrower: 2"                                                                                           -> lar.applicant.race.race2.code.toString,
    "Race of Applicant or Borrower: 3"                                                                                           -> lar.applicant.race.race3.code.toString,
    "Race of Applicant or Borrower: 4"                                                                                           -> lar.applicant.race.race4.code.toString,
    "Race of Applicant or Borrower: 5"                                                                                           -> lar.applicant.race.race5.code.toString,
    "Race of Applicant or Borrower: Free Form Text Field for American Indian or Alaska Native Enrolled or Principal Tribe"       -> lar.applicant.race.otherNativeRace,
    "Race of Applicant or Borrower: Free Form Text Field for Other Asian"                                                        -> lar.applicant.race.otherAsianRace,
    "Race of Applicant or Borrower: Free Form Text Field for Other Pacific Islander"                                             -> lar.applicant.race.otherPacificIslanderRace,
    "Race of Co-Applicant or Co-Borrower: 1"                                                                                     -> lar.coApplicant.race.race1.code.toString,
    "Race of Co-Applicant or Co-Borrower: 2"                                                                                     -> lar.coApplicant.race.race2.code.toString,
    "Race of Co-Applicant or Co-Borrower: 3"                                                                                     -> lar.coApplicant.race.race3.code.toString,
    "Race of Co-Applicant or Co-Borrower: 4"                                                                                     -> lar.coApplicant.race.race4.code.toString,
    "Race of Co-Applicant or Co-Borrower: 5"                                                                                     -> lar.coApplicant.race.race5.code.toString,
    "Race of Co-Applicant or Co-Borrower: Free Form Text Field for American Indian or Alaska Native Enrolled or Principal Tribe" -> lar.coApplicant.race.otherNativeRace,
    "Race of Co-Applicant or Co-Borrower: Free Form Text Field for Other Asian"                                                  -> lar.coApplicant.race.otherAsianRace,
    "Race of Co-Applicant or Co-Borrower: Free Form Text Field for Other Pacific Islander"                                       -> lar.coApplicant.race.otherPacificIslanderRace,
    "Race of Applicant or Borrower Collected on the Basis of Visual Observation or Surname"                                      -> lar.applicant.race.raceObserved.code.toString,
    "Race of Co-Applicant or Co-Borrower Collected on the Basis of Visual Observation or Surname"                                -> lar.coApplicant.race.raceObserved.code.toString,
    "Sex of Applicant or Borrower"                                                                                               -> lar.applicant.sex.sexEnum.code.toString,
    "Sex of Co-Applicant or Co-Borrower"                                                                                         -> lar.coApplicant.sex.sexEnum.code.toString,
    "Sex of Applicant or Borrower Collected on the Basis of Visual Observation or Surname"                                       -> lar.applicant.sex.sexObservedEnum.code.toString,
    "Sex of Co-Applicant or Co-Borrower Collected on the Basis of Visual Observation or Surname"                                 -> lar.coApplicant.sex.sexObservedEnum.code.toString,
    "Age of Applicant or Borrower"                                                                                               -> lar.applicant.age.toString,
    "Age of Co-Applicant or Co-Borrower"                                                                                         -> lar.coApplicant.age.toString,
    "Income"                                                                                                                     -> lar.income,
    "Type of Purchaser"                                                                                                          -> lar.purchaserType.code.toString,
    "Rate Spread"                                                                                                                -> lar.loan.rateSpread,
    "HOEPA Status"                                                                                                               -> lar.hoepaStatus.code.toString,
    "Lien Status"                                                                                                                -> lar.lienStatus.code.toString,
    "Credit Score of Applicant or Borrower"                                                                                      -> lar.applicant.creditScore.toString,
    "Credit Score of Co-Applicant or Co-Borrower"                                                                                -> lar.coApplicant.creditScore.toString,
    "Applicant or Borrower, Name and Version of Credit Scoring Model"                                                            -> lar.applicant.creditScoreType.code.toString,
    "Applicant or Borrower, Name and Version of Credit Scoring Model: Conditional Free Form Text Field for Code 8"               -> lar.applicant.otherCreditScoreModel,
    "Co-Applicant or Co-Borrower, Name and Version of Credit Scoring Model"                                                      -> lar.coApplicant.creditScoreType.code.toString,
    "Co-Applicant or Co-Borrower, Name and Version of Credit Scoring Model: Conditional Free Form Text Field for Code 8"         -> lar.coApplicant.otherCreditScoreModel,
    "Reason for Denial: 1"                                                                                                       -> lar.denial.denialReason1.code.toString,
    "Reason for Denial: 2"                                                                                                       -> lar.denial.denialReason2.code.toString,
    "Reason for Denial: 3"                                                                                                       -> lar.denial.denialReason3.code.toString,
    "Reason for Denial: 4"                                                                                                       -> lar.denial.denialReason4.code.toString,
    "Reason for Denial: Conditional Free Form Text Field for Code 9"                                                             -> lar.denial.otherDenialReason,
    "Total Loan Costs"                                                                                                           -> lar.loanDisclosure.totalLoanCosts,
    "Total Points and Fees"                                                                                                      -> lar.loanDisclosure.totalPointsAndFees,
    "Origination Charges"                                                                                                        -> lar.loanDisclosure.originationCharges,
    "Discount Points"                                                                                                            -> lar.loanDisclosure.discountPoints,
    "Lender Credits"                                                                                                             -> lar.loanDisclosure.lenderCredits,
    "Interest Rate"                                                                                                              -> lar.loan.interestRate,
    "Prepayment Penalty Term"                                                                                                    -> lar.loan.prepaymentPenaltyTerm,
    "Debt-to-Income Ratio"                                                                                                       -> lar.loan.debtToIncomeRatio,
    "Combined Loan-to-Value Ratio"                                                                                               -> lar.loan.combinedLoanToValueRatio,
    "Loan Term"                                                                                                                  -> lar.loan.loanTerm,
    "Introductory Rate Period"                                                                                                   -> lar.loan.introductoryRatePeriod,
    "Balloon Payment"                                                                                                            -> lar.nonAmortizingFeatures.balloonPayment.code.toString,
    "Interest-Only Payments"                                                                                                     -> lar.nonAmortizingFeatures.interestOnlyPayments.code.toString,
    "Negative Amortization"                                                                                                      -> lar.nonAmortizingFeatures.negativeAmortization.code.toString,
    "Other Non-amortizing Features"                                                                                              -> lar.nonAmortizingFeatures.otherNonAmortizingFeatures.code.toString,
    "Property Value"                                                                                                             -> lar.property.propertyValue,
    "Manufactured Home Secured Property Type"                                                                                    -> lar.property.manufacturedHomeSecuredProperty.code.toString,
    "Manufactured Home Land Property Interest"                                                                                   -> lar.property.manufacturedHomeLandPropertyInterest.code.toString,
    "Total Units"                                                                                                                -> lar.property.totalUnits.toString,
    "Multifamily Affordable Units"                                                                                               -> lar.property.multiFamilyAffordableUnits,
    "Submission of Application"                                                                                                  -> lar.applicationSubmission.code.toString,
    "Initially Payable to Your Institution"                                                                                      -> lar.payableToInstitution.code.toString,
    "NMLSR ID"                                                                                                                   -> lar.larIdentifier.NMLSRIdentifier,
    "Automated Underwriting System: 1"                                                                                           -> lar.AUS.aus1.code.toString,
    "Automated Underwriting System: 2"                                                                                           -> lar.AUS.aus2.code.toString,
    "Automated Underwriting System: 3"                                                                                           -> lar.AUS.aus3.code.toString,
    "Automated Underwriting System: 4"                                                                                           -> lar.AUS.aus4.code.toString,
    "Automated Underwriting System: 5"                                                                                           -> lar.AUS.aus5.code.toString,
    "Automated Underwriting System: Conditional Free Form Text Field for Code 5"                                                 -> lar.AUS.otherAUS,
    "Automated Underwriting System Result: 1"                                                                                    -> lar.ausResult.ausResult1.code.toString,
    "Automated Underwriting System Result: 2"                                                                                    -> lar.ausResult.ausResult2.code.toString,
    "Automated Underwriting System Result: 3"                                                                                    -> lar.ausResult.ausResult3.code.toString,
    "Automated Underwriting System Result: 4"                                                                                    -> lar.ausResult.ausResult4.code.toString,
    "Automated Underwriting System Result: 5"                                                                                    -> lar.ausResult.ausResult5.code.toString,
    "Automated Underwriting System Result: Conditional Free Form Text Field for Code 16"                                         -> lar.ausResult.otherAusResult,
    "Reverse Mortgage"                                                                                                           -> lar.reverseMortgage.code.toString,
    "Open-End Line of Credit"                                                                                                    -> lar.lineOfCredit.code.toString,
    "Business or Commercial Purpose"                                                                                             -> lar.businessOrCommercialPurpose.code.toString
  )
}
