podTemplate(label: 'buildHelm', containers: [
    containerTemplate(name: 'helm', image: 'alpine/helm', ttyEnabled: true, command: 'cat')
]) {
    node('buildHelm') {
        init.setEnvironment('keycloak')

        stage('Ambassador Service') {
            if (env.BRANCH_NAME == 'master') {
                container('helm') {
                    sh "kubectl create --namespace=default -f kubernetes/keycloak/keycloak-ambassador.yaml | exit 0"
                }
            }
        }

        stage('Deploy') {
            helm.deploy('modified-lar')
        }
    }
}