image.tag: 16.1.1
startupScripts: 
  script.sh: |
      #!/bin/bash
      printf "\nEnvironment:\n"
      env | sort

      echo "Updated $LOGIN_THEME:"
      cat $LOGIN_THEME

      echo "Cleaning history"
      rm -rf /opt/jboss/keycloak/standalone/configuration/standalone_xml_history/current/*

postgresql:
  # Disable PostgreSQL dependency
  enabled: false

extraEnv: |
  - name: DB_VENDOR
    value: postgres
  - name: DB_ADDR
    value: postgres-postgresql.postgres
  - name: DB_PORT
    value: "5432"
  - name: DB_DATABASE
    value: postgres
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"

args: 
  - "-Dkeycloak.import=/realm/realm.json"

keycloak:
  persistence:
    existingSecret: postgres-credentials
    existingSecretPasswordKey: postgres-password
    existingSecretUsernameKey: postgres-username

extraInitContainers: |
  - name: theme-provider  
    image: hmda/theme-provider:v2.20.7
    imagePullPolicy: Always
    command:
      - sh
    args:
      - -c
      - |
        echo "Copying theme..."
        cp -R /themes/* /theme
    volumeMounts:
      - name: theme
        mountPath: /theme
  - name: spi-provider
    image: hmda/keycloak-spi-provider:v2.7.4
    imagePullPolicy: Always
    command:
      - sh
    args:
      - -c
      - |
        echo "Copying SPI..."
        ls
        cp -rv keycloak-authenticator-hmda-4.2.1.Final.jar /spi
    volumeMounts:
      - name: spi
        mountPath: /spi

extraVolumes: |
  - name: realm-secret
    secret:
      secretName: realm-secret
  - name: theme
    emptyDir: {}
  - name: spi
    emptyDir: {}
extraVolumeMounts: |
  - name: realm-secret
    mountPath: "/realm/"
    readOnly: true
  - name: theme
    mountPath: /opt/jboss/keycloak/themes/hmda
  - name: spi
    mountPath: /opt/jboss/keycloak/standalone/deployments
