podTemplate(label: 'buildSbtPod', containers: [
  containerTemplate(name: 'sbt', image: 'jenkinsxio/builder-scala', ttyEnabled: true, command: 'cat'),
  containerTemplate(name: 'docker', image: 'docker', ttyEnabled: true, command: 'cat'),
  containerTemplate(name: 'helm', image: 'lachlanevenson/k8s-helm', ttyEnabled: true, command: 'cat')
],
volumes: [
  hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
]) {
   node('buildSbtPod') {
     def repo = checkout scm
     def gitCommit = repo.GIT_COMMIT
     def gitBranch = repo.GIT_BRANCH
     def gitDescribe = sh(returnStdout: true, script: 'git describe --always --tags')
     def gitTag = sh(returnStdout: true, script: "git tag --sort version:refname | tail -1").trim()
     def commitId = sh(returnStdout: true, script: 'git rev-parse HEAD')
     def result = sh(returnStatus: true, script: "git log -1 | grep '\\[deploy pr\\]'")
     def isDeployPR = result == 0 ? true : false
     if (gitBranch == "master") {
       env.DOCKER_TAG = "latest"
     }
     else if (isDeployPR) {
        env.DOCKER_TAG = "${env.JOB_NAME?.split('/')[1]}${env.BUILD_NUMBER}"
        gitTag = env.DOCKER_TAG+gitTag
     }
     else {
       env.DOCKER_TAG = env.TAG_NAME
     }

     println "DOCKER_TAG: ${env.DOCKER_TAG}, gitDescribe: ${gitDescribe}, gitTag: ${gitTag}, commitId: ${commitId}, isDeployPR: ${isDeployPR}"

     stage('Build Scala Code and Generate Dockerfile') {
       container('sbt') {
         sh "sbt -batch hmda-platform/docker:stage"
       }
     }

    stage('Build And Publish Docker Image') {
      container('docker') {
        withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub',
          usernameVariable: 'DOCKER_HUB_USER', passwordVariable: 'DOCKER_HUB_PASSWORD']]) {
          withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'hmda-platform-jenkins-service',
            usernameVariable: 'DTR_USER', passwordVariable: 'DTR_PASSWORD']]) {
            withCredentials([string(credentialsId: 'internal-docker-registry', variable: 'DOCKER_REGISTRY_URL')]){
              sh "docker build --rm -t=${env.DOCKER_HUB_USER}/hmda-platform hmda/target/docker/stage"
              if (env.TAG_NAME != null || gitBranch == "master" || isDeployPR) {

                sh """
                  docker tag ${env.DOCKER_HUB_USER}/hmda-platform ${env.DOCKER_HUB_USER}/hmda-platform:${env.DOCKER_TAG}
                  docker login -u ${env.DOCKER_HUB_USER} -p ${env.DOCKER_HUB_PASSWORD} 
                  docker push ${env.DOCKER_HUB_USER}/hmda-platform:${env.DOCKER_TAG}
                  docker tag ${env.DOCKER_HUB_USER}/hmda-platform:${env.DOCKER_TAG} ${DOCKER_REGISTRY_URL}/${env.DOCKER_HUB_USER}/hmda-platform:${env.DOCKER_TAG}
                  docker login ${DOCKER_REGISTRY_URL} -u ${env.DTR_USER} -p ${env.DTR_PASSWORD}
                  docker push ${DOCKER_REGISTRY_URL}/${env.DOCKER_HUB_USER}/hmda-platform:${env.DOCKER_TAG}
                  docker images
                  docker image prune -f
                  docker images
                  docker ps -a
                """
              }
            }
          }
        }
      }
    }

    stage('Deploy') {
        if (env.BRANCH_NAME == 'master' || isDeployPR) {
            container('helm') {
                //run packaging with app version and version
                dir("kubernetes/hmda-platform") {
                    sh """
                        helm init --client-only
                        helm package --app-version="${commitId[0..7]}" --version=${gitTag} .
                        tar --strip-components=1 -zxf hmda-platform-*
                        rm -rf hmda-platform-*.tgz
                    """
                }

                sh """
                  helm upgrade --install --force \
                  --namespace=default \
                  --values=kubernetes/hmda-platform/values.yaml \
                  --set image.tag="${DOCKER_TAG}" \
                  --set service.name=hmda-platform-api \
                  --set image.pullPolicy=Always \
                  hmda-platform kubernetes/hmda-platform
                """
            }
        }
    }

   }

}
