apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hmda-analytics.fullname" . }}
  labels:
    app: {{ include "hmda-analytics.name" . }}
    chart: {{ include "hmda-analytics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "hmda-analytics.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "hmda-analytics.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.service.account.name }}
      volumes:
        - name: rds-secret-provider-vol
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: irsa-hmda-rds-secrets-provider
        - name: actor-persistence-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: irsa-actor-persistence-secrets-provider
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/America/New_York
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name: rds-secret-provider-vol
              mountPath: /mnt/rds-secrets-store
            - name: tz-config
              mountPath: /etc/localtime
            - name: actor-persistence-secrets
              mountPath: /mnt/actor-persistence-secrets
              readOnly: true
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL            
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ACTOR_PERSISTENCE_PG_HOST
              valueFrom:
                secretKeyRef:
                  name: irsa-actor-persistence-secrets
                  key: host
            - name: ACTOR_PERSISTENCE_PG_SCHEMA
              value: actor_persistence_beta
            - name: ACTOR_PERSISTENCE_PG_DB
              valueFrom:
                secretKeyRef:
                  name: irsa-actor-persistence-secrets
                  key: database
            - name: ACTOR_PERSISTENCE_PG_USER
              valueFrom:
                secretKeyRef:
                  name: irsa-actor-persistence-secrets
                  key: username
            - name: ACTOR_PERSISTENCE_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: irsa-actor-persistence-secrets
                  key: password
            - name: ACTOR_PERSISTENCE_PG_SSL_ENABLED
              value: "on"
            - name: ACTOR_PERSISTENCE_PG_SSL_MODE
              value: allow
            - name: ACTOR_PERSISTENCE_PG_BUFFER_SIZE
              value: "2000"
            - name: ACTOR_PERSISTENCE_PG_REFRESH_INTERVAL
              value: "1s"
            - name: KAFKA_ANALYTICS_TOPIC
              value: {{.Values.kafka.analyticsTopic}}
            - name: KAFKA_SIGN_TOPIC
              value: {{.Values.kafka.signTopic}}
            - name: KAFKA_ANALYTICS_GROUP
              value: {{.Values.kafka.analyticsGroup}}
            {{- if .Values.kafka.security }}
            - name: KAFKA_SECURITY
              value: {{.Values.kafka.security}}
            {{- end }}              
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: irsa-platform-rds-secrets
                  key: host
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: irsa-platform-rds-secrets
                  key: database
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: irsa-platform-rds-secrets
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: irsa-platform-rds-secrets
                  key: password
            - name: BANK_FILTER_LIST
              valueFrom:
                configMapKeyRef:
                  name: bank-filter-configmap
                  key: bank-filter-list
            - name: KAFKA_CLUSTER_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: kafka.hosts
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
