apiVersion: v1
kind: ConfigMap
metadata:
  name: hmda-data-publisher-dynamic-schedule-config
 data:
  COMBINED_MLAR_PUBLIC_SCHEDULE_CRON: 0 00 16 ? * SUN *
  COMBINED_MLAR_PUBLIC_SCHEDULE_YEARS: '2022'
  LAR_LOAN_LIMIT_SCHEDULE_CRON: 0 10 5 ? * MON *
  LAR_LOAN_LIMIT_SCHEDULE_YEARS: 2021,2022,2023
  LAR_PUBLIC_SCHEDULE_CRON: 0 00 10 ? * SUN *
  LAR_PUBLIC_SCHEDULE_YEARS: 2021,2022
  LAR_QUARTERLY_SCHEDULE_CRON: 0 0 0 23 4 ? 2079
  LAR_QUARTERLY_SCHEDULE_YEARS: '2023'
  LAR_SCHEDULE_CRON: 0 00 14 ? * SUN *
  LAR_SCHEDULE_YEARS: 2021,2022
  PANEL_SCHEDULE_CRON: 0 10 8 ? * SUN *
  PANEL_SCHEDULE_YEARS: 2021,2022
  SPECIFIC_LAR_SCHEDULE_CRON: 0 30 4 * * ?
  SPECIFIC_LAR_SCHEDULE_YEARS: '2023'
  SPECIFIC_PANEL_SCHEDULE_CRON: 0 20 4 * * ?
  SPECIFIC_PANEL_SCHEDULE_YEARS: '2023'
  SPECIFIC_TS_SCHEDULE_CRON: 0 10 4 * * ?
  SPECIFIC_TS_SCHEDULE_YEARS: '2023'
  TS_PUBLIC_SCHEDULE_CRON: 0 00 8 ? * SUN *
  TS_PUBLIC_SCHEDULE_YEARS: 2021,2022
  TS_QUARTERLY_SCHEDULE_CRON: 0 0 0 23 4 ? 2079
  TS_QUARTERLY_SCHEDULE_YEARS: '2023'
  TS_SCHEDULE_CRON: 0 00 7 ? * SUN *
  TS_SCHEDULE_YEARS: 2021,2022
