kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
     storage: 10Gi
