apiVersion: v1
kind: Service
metadata:
  name: {{ include "submission-errors.fullname" . }}
  labels:
    service: {{ include "submission-errors.fullname" . }}
spec:
  selector:
    app: {{ include "submission-errors.name" . }}
  ports:
    - port: 8070
      targetPort: 8070
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    service: {{ include "submission-errors.fullname" . }}-mapping
  name: {{ include "submission-errors.fullname" . }}-mapping
spec:
  {{- if .Values.ambassador_id }}
  ambassador_id: {{ .Values.ambassador_id }}
  {{- end}}
  {{- if .Values.ambassador_host }}
  host: {{ .Values.ambassador_host }}
  {{- end}}
  timeout_ms: 300000
  prefix: /submission-errors/
  rewrite: /
  service: {{ include "submission-errors.fullname" . }}:8070