pipeline {
  agent {
    label 'hmdaops'
  }

  stages {
    stage('init') {
      steps {
        script {
          init.setEnvironment('email_service')
          init.checkForChanges('email-service')
        }
      }
    }

    stage('Build Scala Code and Generate Dockerfile') {
      agent {
        docker {
          image 'hmda/sbt'
          reuseNode true
        }
      }
      steps {
        sh """find . -name target -type d -prune -exec rm -rf {} \\;"""
        sh """find . -name test -type d -prune -exec rm -rf {} \\;"""
        sh "sbt -Dsbt.global.base=.sbt -Dsbt.boot.directory=.sbt -Dsbt.ivy.home=.ivy2 -batch clean email-service/docker:stage"
        sh "rm -rf data"
      }
    }

    stage('Build And Publish Docker Image') {
      steps {
        script {
          withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub',
            usernameVariable: 'DOCKER_HUB_USER', passwordVariable: 'DOCKER_HUB_PASSWORD']]) {
            withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dtr-ext-jenkins-service',
              usernameVariable: 'DTR_USER', passwordVariable: 'DTR_PASSWORD']]) {
                dockerBuild.sbtBuild('email-service')
                scanImage('hmda/email-service', env.DOCKER_TAG)
            }
          }
        }
      }
    }

    stage('Deploy') {
      agent {
        docker {
          image 'hmda/helm:2.16.6'
          reuseNode true
          args '--entrypoint=\'\''
        }
      }
      steps {
        script {
          withCredentials([file(credentialsId: 'hmda-ops-kubeconfig', variable: 'KUBECONFIG')]) {
            if (env.DOCKER_PUSH == 'true') {
              helm.deploy('email-service')
            }
          }
        }
      }
    }

    stage('Docker Clean Up') {
      steps {
        script {
          dockerBuild.clean()
        }
      }
    }
  }

}
