INSERT INTO public.loanapplicationregister2018(
	id, lei, uli, application_date, loan_type, loan_purpose, preapproval, construction_method, occupancy_type, loan_amount, action_taken_type, action_taken_date, street, city, state, zip, county, tract, ethnicity_applicant_1, ethnicity_applicant_2, ethnicity_applicant_3, ethnicity_applicant_4, ethnicity_applicant_5, other_hispanic_applicant, ethnicity_co_applicant_1, ethnicity_co_applicant_2, ethnicity_co_applicant_3, ethnicity_co_applicant_4, ethnicity_co_applicant_5, other_hispanic_co_applicant, ethnicity_observed_applicant, ethnicity_observed_co_applicant, race_applicant_1, race_applicant_2, race_applicant_3, race_applicant_4, race_applicant_5, other_native_race_applicant, other_asian_race_applicant, other_pacific_race_applicant, race_co_applicant_1, race_co_applicant_2, race_co_applicant_3, race_co_applicant_4, race_co_applicant_5, other_native_race_co_applicant, other_asian_race_co_applicant, other_pacific_race_co_applicant, race_observed_applicant, race_observed_co_applicant, sex_applicant, sex_co_applicant, observed_sex_applicant, observed_sex_co_applicant, age_applicant, age_co_applicant, income, purchaser_type, rate_spread, hoepa_status, lien_status, credit_score_applicant, credit_score_co_applicant, credit_score_type_applicant, credit_score_model_applicant, credit_score_type_co_applicant, credit_score_model_co_applicant, denial_reason1, denial_reason2, denial_reason3, denial_reason4, other_denial_reason, total_loan_costs, total_points, origination_charges, discount_points, lender_credits, interest_rate, payment_penalty, debt_to_incode, loan_value_ratio, loan_term, rate_spread_intro, baloon_payment, insert_only_payment, amortization, other_amortization, property_value, home_security_policy, lan_property_interest, total_uits, mf_affordable, application_submission, payable, nmls, aus1, aus2, aus3, aus4, aus5, other_aus, aus1_result, aus2_result, aus3_result, aus4_result, aus5_result, other_aus_result, reverse, aus_result, reverse_mortgage, line_of_credits, business_or_commercial)
	VALUES (1,
			'FJFJOIHEU12312',
			'ULI_VALUE',
			'2008-04-30',
			20,
			1,
			1,
			2,
			23,
			5000.24,
			50,
			2,
			'123 Fake Drive',
			'Fake Town',
			'DC',
			'22192',
			'PWC',
			'Some_TRACT',
			1,
			2,
			3,
			4,
			5,
			'Other Applicant',
			6,
			7,
			8,
			9,
			10,
			'Other Co Applicant',
			9,
			89,
			99,
			1,
			2,
			4,
			5,
			'6',
			'other app',
			'otehr 2',
			5,
			1,
			2,
			4,
			5,
			'54',
			'other 56',
			'other87',
			44,
			3,
			4,
			9,
			4,
			6,
			7,
			5,
			'20,000',
			2,
			'3.0',
			3,
			9,
			400,
			900,
			560,
			'700',
			800,
			'800',
			1,
			1,
			1,
			1,
			'hmda',
			'50,000',
			'400',
			'5000',
			'80',
			'9000',
			'9.0',
			'7000',
			'1 to 50',
			'5/60',
			'72 months',
			'60',
			0,
			9,
			3,
			3,
			'something value',
			8,
			4,
			4,
			'some affordable',
			2,
			900,
			'nmls col',
			1,
			2,
			3,
			4,
			5,
			'otheraus col',
			1,
			2,
			3,
			7,
			8,
			'other aus',
			7,
			9,
			2, 4, 3);