podTemplate(label: 'buildSbtPod', containers: [
  containerTemplate(name: 'sbt', image: 'jenkinsxio/builder-scala', ttyEnabled: true, command: 'cat'),
  containerTemplate(name: 'docker', image: 'docker', ttyEnabled: true, command: 'cat'),
  containerTemplate(name: 'helm', image: 'alpine/helm', ttyEnabled: true, command: 'cat')
],
volumes: [
  hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
]) {
  node('buildSbtPod') {
    init.setEnvironment('rate_limit')
    init.checkForChanges('rate-limit')

    stage('Build Scala Code and Generate Dockerfile') {
      container('sbt') {
        sh "sbt -batch rate-limit/docker:stage"
      }
    }

    stage('Build And Publish Docker Image') {
      container('docker') {
        withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub',
          usernameVariable: 'DOCKER_HUB_USER', passwordVariable: 'DOCKER_HUB_PASSWORD']]) {
          withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'hmda-platform-jenkins-service',
            usernameVariable: 'DTR_USER', passwordVariable: 'DTR_PASSWORD']]) {
            withCredentials([string(credentialsId: 'internal-docker-registry', variable: 'DOCKER_REGISTRY_URL')]){
              dockerBuild.sbtBuild('rate-limit')
              security.dockerImageScan('rate-limit', env.DOCKER_TAG)
            }
          }
        }
      }
    }

    stage('Deploy') {
      if ((env.BRANCH_NAME == 'master' || isDeployPR) && deploy) {
        container('helm') {
          helm.deploy('rate-limit')
        }
      }
    }

    stage('Docker Clean Up') {
      container('docker') {
        dockerBuild.clean()
      }
    } 

  }
}
