package hmda.model.filing.lar

import enums._

case class LoanApplicationRegister(
    id: Int = 2,
    LEI: String,
    loan: Loan,
    preapproval: PreapprovalEnum,
    actionTakenType: ActionTakenTypeEnum,
    actionTakenDate: Int,
    geography: Geography,
    applicant: Applicant,
    coApplicant: Applicant,
    purchaserType: PurchaserEnum,
    rateSpread: String,
    hoepaStatus: HOEPAStatusEnum,
    lienStatus: LienStatusEnum,
    denial: Denial,
    otherDenialReason: String,
    totalLoanCosts: String,
    totalPointsAndFees: String,
    originationCharges: String,
    discountPoints: String,
    lenderCredits: String,
    interestRate: String,
    prepaymentPenaltyTerm: String,
    debtToIncomeRatio: String,
    loanToValueRatio: String,
    loanTerm: String,
    introductoryRatePeriod: String,
    balloonPayment: BalloonPaymentEnum,
    interestOnlyPayments: InterestOnlyPaymentsEnum,
    negativeAmortization: NegativeAmortizationEnum,
    otherNonAmortizingFeatures: OtherNonAmortizingFeaturesEnum,
    propertyValue: String,
    manufacturedHomeSecuredProperty: ManufacturedHomeSecuredPropertyEnum,
    totalUnits: Int,
    multiFamilyAffordableUnits: String,
    applicationSubmission: ApplicationSubmissionEnum,
    payableToInstitution: PayableToInstitutionEnum,
    NMLSRIdentified: String,
    AUS: AutomatedUnderwritingSystem,
    otherAUS: String,
    ausResult: AutomatedUnderwritingSystemResult,
    otherAusResult: String,
    reverseMortgage: MortgageTypeEnum,
    lineOfCredit: LineOfCreditEnum,
    businessOrCommercialPurpose: BusinessOrCommercialBusinessEnum
)
