package hmda.model.filing.lar

import enums._

case class LoanApplicationRegister(
    id: Int = 2,
    LEI: Option[String] = None,
    loan: Loan,
    preapproval: PreapprovalEnum,
    actionTakenType: ActionTakenTypeEnum,
    actionTakenDate: Int,
    geography: Geography,
    applicant: Applicant,
    coApplicant: Applicant,
    purchaserType: PurchaserEnum,
    rateSpread: String,
    hoepaStatus: HOEPAStatusEnum,
    lienStatus: LienStatusEnum,
    denial: Denial,
    otherDenialReason: String,
    totalLoanCosts: String,
    totalPointsAndFees: String,
    originationCharges: Option[String] = None,
    discountPoints: Option[String] = None,
    lenderCredits: Option[String] = None,
    interestRate: Option[String] = None,
    prepaymentPenaltyTerm: String,
    debtToIncomeRatio: Option[String] = None,
    loanToValueRatio: Option[String] = None,
    loanTerm: String,
    introductoryRatePeriod: String,
    balloonPayment: BalloonPaymentEnum,
    interestOnlyPayments: InterestOnlyPaymentsEnum,
    negativeAmortization: NegativeAmortizationEnum,
    otherNonAmortizingFeatures: OtherNonAmortizingFeaturesEnum,
    propertyValue: String,
    manufacturedHomeSecuredProperty: Option[ManufacturedHomeSecuredPropertyEnum] = None,
    manufacturedHomeLandPropertyInterestEnum: Option[ManufacturedHomeLandPropertyInterestEnum] = None,
    totalUnits: Option[Int] = None,
    multiFamilyAffordableUnits: Option[String] = None,
    applicationSubmission: ApplicationSubmissionEnum,
    payableToInstitution: PayableToInstitutionEnum,
    NMLSRIdentified: String,
    AUS: Option[AutomatedUnderwritingSystem] = None,
    otherAUS: Option[String] = None,
    ausResult: Option[AutomatedUnderwritingSystemResult] = None,
    otherAusResult: Option[String] = None,
    reverseMortgage: Option[MortgageTypeEnum] = None,
    lineOfCredit: Option[LineOfCreditEnum] = None,
    businessOrCommercialPurpose: Option[BusinessOrCommercialBusinessEnum] = None
)
