package hmda.model.filing.lar

import enums._

case class LoanApplicationRegister(
    id: Int = 2,
    LEI: String,
    loan: Loan,
    preapproval: PreapprovalEnum,
    actionTakenType: ActionTakenTypeEnum,
    actionTakenDate: Int,
    geography: Geography,
    applicant: Applicant,
    coApplicant: Applicant,
    purchaserType: PurchaserEnum,
    rateSpread: String,
    hoepaStatus: HOEPAStatusEnum,
    lienStatus: LienStatusEnum,
    denial: Denial,
    otherDenialReason: String,
    totalLoanCosts: String,
    totalPointsAndFees: String,
    originationCharges: Option[String],
    discountPoints: Option[String],
    lenderCredits: Option[String],
    interestRate: Option[String],
    prepaymentPenaltyTerm: String,
    debtToIncomeRatio: Option[String],
    loanToValueRatio: Option[String],
    loanTerm: String,
    introductoryRatePeriod: String,
    balloonPayment: BalloonPaymentEnum,
    interestOnlyPayments: InterestOnlyPaymentsEnum,
    negativeAmortization: NegativeAmortizationEnum,
    otherNonAmortizingFeatures: OtherNonAmortizingFeaturesEnum,
    propertyValue: String,
    manufacturedHomeSecuredProperty: Option[ManufacturedHomeSecuredPropertyEnum],
    manufacturedHomeLandPropertyInterestEnum: Option[ManufacturedHomeLandPropertyInterestEnum],
    totalUnits: Option[Int],
    multiFamilyAffordableUnits: Option[String],
    applicationSubmission: ApplicationSubmissionEnum,
    payableToInstitution: PayableToInstitutionEnum,
    NMLSRIdentified: String,
    AUS: Option[AutomatedUnderwritingSystem],
    otherAUS: Option[String],
    ausResult: Option[AutomatedUnderwritingSystemResult],
    otherAusResult: Option[String],
    reverseMortgage: Option[MortgageTypeEnum],
    lineOfCredit: LineOfCreditEnum,
    businessOrCommercialPurpose: Option[BusinessOrCommercialBusinessEnum]
)
