---
apiVersion: v1
kind: Service
metadata:
  name: file-proxy
  labels:
    service: file-proxy
spec:
  selector:
    app: file-proxy
  ports:
    - port: 9091
      protocol: TCP
      targetPort: 9091
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    service: {{ include "file-proxy.fullname" . }}-mapping
  name: {{ include "file-proxy.fullname" . }}-mapping
spec:
  {{- if .Values.ambassador_id }}
  ambassador_id: {{ .Values.ambassador_id }}
  {{- end}}
  {{- if .Values.ambassador_host }}
  host: {{ .Values.ambassador_host }}
  {{- end}}
  prefix: /file/
  rewrite: /file/
  service: {{ include "file-proxy.fullname" . }}:{{ .Values.service.port }}
  timeout_ms: 300000
  add_response_headers:
    referrer-policy:
      value: strict-origin
      append: False
    content-security-policy:
      append: False
      value: "default-src 'self'; script-src 'self'; img-src 'self'; style-src 'self'; font-src 'self'; object-src 'none'; frame-src 'self'; connect-src 'self'"
    permissions-policy:
      value: "autoplay=(), encrypted-media=(), fullscreen=(), geolocation=(), microphone=(), midi=()"
    x-frame-Options:
      value : "SAMEORIGIN"
    x-content-type-options:
      value : nosniff
    strict-transport-security:
      value: "max-age=31536000; includeSubDomains; preload"
    x-xss-protection:
      value: "1; mode=block"
  remove_response_headers:
    - Access-Control-Allow-Origin
    - x-envoy-upstream-service-time
    - x-forwarded-host
    - x-host
    - x-forwarded-server
#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    service: {{ include "file-proxy.fullname" . }}-ambassador
#  name: {{ include "file-proxy.fullname" . }}-ambassador
#  annotations:
#    getambassador.io/config: |
#      apiVersion: ambassador/v2
#      kind: Mapping
#      name: file_proxy_mapping
#      ambassador_id: ambassador-default-1
#      prefix: /file/
#      rewrite: /file/
#      service: {{ include "file-proxy.fullname" . }}:{{ .Values.service.port }}
#      timeout_ms: 300000
#      add_response_headers:
#        referrer-policy:
#          value: strict-origin
#          append: False
#        content-security-policy:
#          append: False
#          value: "default-src 'self'; script-src 'self'; img-src 'self'; style-src 'self'; font-src 'self'; object-src 'none'; frame-src 'self'; connect-src 'self'"
#        permissions-policy:
#          value: "autoplay=(), encrypted-media=(), fullscreen=(), geolocation=(), microphone=(), midi=()"
#        x-frame-Options:
#          value : "SAMEORIGIN"
#        x-content-type-options:
#          value : nosniff
#        strict-transport-security:
#          value: "max-age=31536000; includeSubDomains; preload"
#        x-xss-protection:
#          value: "1; mode=block"
#      remove_response_headers:
#      - Access-Control-Allow-Origin
#      - x-envoy-upstream-service-time
#      - x-forwarded-host
#      - x-host
#      - x-forwarded-server
#spec:
#  clusterIP: None
