apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "irs-publisher.fullname" . }}
  annotations:
    reloader.stakater.com/search: "true"
    downscaler/uptime: Mon-Fri 10:00-23:00 UTC
  labels:
    app: {{ include "irs-publisher.name" . }}
    chart: {{ include "irs-publisher.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "irs-publisher.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "irs-publisher.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: hmda-platform-irsa
      volumes:
        - name: actor-persistence-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: irsa-actor-persistence-secrets-provider
        - name: akka-license
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: irsa-akka-license-provider
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name: actor-persistence-secrets
              mountPath: /mnt/actor-persistence-secrets
              readOnly: true
            - name: akka-license
              mountPath: /mnt/akka-license
              readOnly: true
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL            
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: "4"
              memory: "2200Mi"
          env:
            - name: AKKA_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: irsa-akka-license-key
                  key: key
            - name: ACTOR_PERSISTENCE_PG_HOST
              valueFrom:
                secretKeyRef:
                  name: irsa-actor-persistence-secrets
                  key: host
            - name: ACTOR_PERSISTENCE_PG_SCHEMA
              value: actor_persistence_beta
            - name: ACTOR_PERSISTENCE_PG_DB
              valueFrom:
                secretKeyRef:
                  name: irsa-actor-persistence-secrets
                  key: database
            - name: ACTOR_PERSISTENCE_PG_USER
              valueFrom:
                secretKeyRef:
                  name: irsa-actor-persistence-secrets
                  key: username
            - name: ACTOR_PERSISTENCE_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: irsa-actor-persistence-secrets
                  key: password
            - name: ACTOR_PERSISTENCE_PG_SSL_ENABLED
              value: "on"
            - name: ACTOR_PERSISTENCE_PG_SSL_MODE
              value: allow
            - name: ACTOR_PERSISTENCE_PG_BUFFER_SIZE
              value: "2000"
            - name: ACTOR_PERSISTENCE_PG_REFRESH_INTERVAL
              value: "1s"
            - name: KAFKA_IRS_TOPIC
              value: {{.Values.kafka.irsTopic}}
            - name: KAFKA_SIGN_TOPIC
              value: {{.Values.kafka.signTopic}}
            - name: KAFKA_IRS_GROUP
              value: {{.Values.kafka.irsGroup}}
            {{- if .Values.kafka.security }}
            - name: KAFKA_SECURITY
              value: {{.Values.kafka.security}}
            {{- end }}
            - name: BANK_FILTER_LIST
              valueFrom:
                configMapKeyRef:
                  name: bank-filter-configmap
                  key: bank-filter-list
            - name: KAFKA_CLUSTER_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: kafka.hosts
            - name: AWS_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: s3-configmap
                  key: aws-environment
            - name: S3_PUBLIC_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: s3-configmap
                  key: s3-public-bucket
            - name: HTTP_CENSUS_HOST
              valueFrom:
                configMapKeyRef:
                  name: http-configmap
                  key: census.host
            - name: HTTP_CENSUS_PORT
              valueFrom:
                configMapKeyRef:
                  name: http-configmap
                  key: census.port
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
