pipeline {
  agent any

  tools {nodejs "node"}

    stages {
        stage('Build') {
            steps {
            echo 'Building..'
            script {
            env.NODEJS_HOME = "${tool 'node'}"
            env.PATH="${env.NODEJS_HOME}/bin:${env.PATH}"
            }
            sh 'node -version'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}