name: Dockerhub login

on:
  pull_request:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Debug secrets
        run: |
          echo "Username:  ${secrets.DOCKERHUB_USERNAME}"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}