name: HMDA Docker Hub Image Push

on:
  push:
    tags:
      - '*'           # Push events to every tag not containing /

env:
  REGISTRY: hmda/hmda-platform

jobs:
  push_to_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Build image of HMDA Platform only
        run: |
          sbt "project hmda-platform" dockerPublishLocalSkipTests

      - name: Tag Docker image
        run: docker tag $(docker images --filter=reference="hmda/hmda-platform:latest" --format "{{.ID}}") ${{ env.REGISTRY }}:${{ github.ref_name }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        run: docker push ${{ env.REGISTRY }}:${{ github.ref_name }}