name: Dockerhub login

on:
  pull_request:
    branches: master

permissions: read-all

jobs:
  login:
    runs-on: ubuntu-latest
    environment: development_environment
    steps:
      - name: Debug secrets
        run: |
          echo "Test secret encrypted:  ${{ secrets.TEST_SECRET }}"
          echo "Blank null secret:  ${{ secrets.NULL_SECRET }}"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}