name: HMDA Unit Tests

on:
  pull_request:
    branches:
      - master

jobs:
  hmda_platform_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run hmda-platform Tests
        run: |
          sbt "project hmda-platform" "testOnly -- -l actions-ignore" 2>&1 | tee -a log-file
        continue-on-error: true

      - name: Check Test Results
        run: |
          if [ $(grep 'All tests passed.' log-file | wc -l) -ne 1 ]; then
            echo "One or more projects had failures. Please review the logs."
            exit 1
          else
            echo "All tests passed."
            exit 0
          fi

  check_digit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run check-digit Tests
        run: |
          sbt "project check-digit" "testOnly -- -l actions-ignore" 2>&1 | tee -a log-file
        continue-on-error: true

      - name: Check Test Results
        run: |
          if [ $(grep 'All tests passed.' log-file | wc -l) -ne 1 ]; then
            echo "One or more projects had failures. Please review the logs."
            exit 1
          else
            echo "All tests passed."
            exit 0
          fi

  common_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run common Tests
        run: |
          sbt "project common" "testOnly -- -l actions-ignore" 2>&1 | tee -a log-file
        continue-on-error: true

      - name: Check Test Results
        run: |
          if [ $(grep 'All tests passed.' log-file | wc -l) -ne 1 ]; then
            echo "One or more projects had failures. Please review the logs."
            exit 1
          else
            echo "All tests passed."
            exit 0
          fi

  data_browser_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run data-browser Tests
        run: |
          sbt "project data-browser" "testOnly -- -l actions-ignore" 2>&1 | tee -a log-file
        continue-on-error: true

      - name: Check Test Results
        run: |
          if [ $(grep 'All tests passed.' log-file | wc -l) -ne 1 ]; then
            echo "One or more projects had failures. Please review the logs."
            exit 1
          else
            echo "All tests passed."
            exit 0
          fi

  hmda_analytics_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run hmda-analytics Tests
        run: |
          sbt "project hmda-analytics" "testOnly -- -l actions-ignore" 2>&1 | tee -a log-file
        continue-on-error: true

      - name: Check Test Results
        run: |
          if [ $(grep 'All tests passed.' log-file | wc -l) -ne 1 ]; then
            echo "One or more projects had failures. Please review the logs."
            exit 1
          else
            echo "All tests passed."
            exit 0
          fi

  hmda_data_publisher_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run hmda-data-publisher Tests
        run: |
          sbt "project hmda-data-publisher" "testOnly -- -l actions-ignore" 2>&1 | tee -a log-file
        continue-on-error: true

      - name: Check Test Results
        run: |
          if [ $(grep 'All tests passed.' log-file | wc -l) -ne 1 ]; then
            echo "One or more projects had failures. Please review the logs."
            exit 1
          else
            echo "All tests passed."
            exit 0
          fi

  hmda_quarterly_data_service_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run hmda-quarterly-data-service Tests
        run: |
          sbt "project hmda-quarterly-data-service" "testOnly -- -l actions-ignore" 2>&1 | tee -a log-file
        continue-on-error: true

      - name: Check Test Results
        run: |
          if [ $(grep 'All tests passed.' log-file | wc -l) -ne 1 ]; then
            echo "One or more projects had failures. Please review the logs."
            exit 1
          else
            echo "All tests passed."
            exit 0
          fi

  hmda_reporting_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run hmda-reporting Tests
        run: |
          sbt "project hmda-reporting" "testOnly -- -l actions-ignore" 2>&1 | tee -a log-file
        continue-on-error: true

      - name: Check Test Results
        run: |
          if [ $(grep 'All tests passed.' log-file | wc -l) -ne 1 ]; then
            echo "One or more projects had failures. Please review the logs."
            exit 1
          else
            echo "All tests passed."
            exit 0
          fi

  institutions_api_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run institutions-api Tests
        run: |
          sbt "project institutions-api" "testOnly -- -l actions-ignore" 2>&1 | tee -a log-file
        continue-on-error: true

      - name: Check Test Results
        run: |
          if [ $(grep 'All tests passed.' log-file | wc -l) -ne 1 ]; then
            echo "One or more projects had failures. Please review the logs."
            exit 1
          else
            echo "All tests passed."
            exit 0
          fi

  modified_lar_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run modified-lar Tests
        run: |
          sbt "project modified-lar" "testOnly -- -l actions-ignore" 2>&1 | tee -a log-file
        continue-on-error: true

      - name: Check Test Results
        run: |
          if [ $(grep 'All tests passed.' log-file | wc -l) -ne 1 ]; then
            echo "One or more projects had failures. Please review the logs."
            exit 1
          else
            echo "All tests passed."
            exit 0
          fi

  rate_limit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run rate-limit Tests
        run: |
          sbt "project rate-limit" "testOnly -- -l actions-ignore" 2>&1 | tee -a log-file
        continue-on-error: true

      - name: Check Test Results
        run: |
          if [ $(grep 'All tests passed.' log-file | wc -l) -ne 1 ]; then
            echo "One or more projects had failures. Please review the logs."
            exit 1
          else
            echo "All tests passed."
            exit 0
          fi

  ratespread_calculator_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run ratespread-calculator Tests
        run: |
          sbt "project ratespread-calculator" "testOnly -- -l actions-ignore" 2>&1 | tee -a log-file
        continue-on-error: true

      - name: Check Test Results
        run: |
          if [ $(grep 'All tests passed.' log-file | wc -l) -ne 1 ]; then
            echo "One or more projects had failures. Please review the logs."
            exit 1
          else
            echo "All tests passed."
            exit 0
          fi
  submission_errors_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run submission-errors Tests
        run: |
          sbt "project submission-errors" "testOnly -- -l actions-ignore" 2>&1 | tee -a log-file
        continue-on-error: true

      - name: Check Test Results
        run: |
          if [ $(grep 'All tests passed.' log-file | wc -l) -ne 1 ]; then
            echo "One or more projects had failures. Please review the logs."
            exit 1
          else
            echo "All tests passed."
            exit 0
          fi